#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), "pre-commit-hooks", "hook"))

hook = Hook.new
hook.check_syntax
hook.check_erb
hook.check_best_practices
hook.warnning_on("WTF?")
hook.warnning_on("console.log")
hook.warnning_on("binding.pry")

exit hook.results
