#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), "pre-commit-hooks", "hook"))

Hook.results do
  do_not_stop_on_warnings 

  check_ruby_syntax
  check_erb
  check_best_practices
  warning_on "WTF?", "binding.pry"
  warning_on "console.log", "debugger" {:in => [:js]}
end
